### ISSUE TITLE
Visual studio is unable to detech the framework version for template

### ISSUE THREAD

**Issue by mahibisht** [drwatson1/AspNet-WebApi#2] opened 2020-04-28 17:59 UTC
![image](https://user-images.githubusercontent.com/4409020/80521117-18b13880-89a8-11ea-8347-557a4f0deff9.png)

**Comment by drwatson1** [comment] 2020-05-23 06:56
The template uses the 4.7.1 version of .Net Framework. Probably, you don't have it installed. With the 4.7.1 and later versions installed you should see that:

![image](https://user-images.githubusercontent.com/18326302/82723957-35a50700-9cdb-11ea-9798-bdacd61b18a7.png)

Please, can you install the 4.7.1 version and check this out again? If it solves the problem I'll close the issue.

I think, I should write it down somewhere in documentation.

**Comment by drwatson1** [comment] 2020-05-23 08:32
I've added information about it in documentation to make this issue will not happen in the future.

I close the issue, but feel free to reopen it if the problem is still there.

**Closed by drwatson1** 2020-05-23 08:32 UTC
